HeadHunterProject/HeadHunterProject/Models/Candidat.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace HeadHunterProject.Models
{
    public class Candidat
    {
        public int Id { get; set; }
        [Required, StringLength(40)]
        public string Nom { get; set; }

        [Required, StringLength(50)]
        public string Prenom { get; set; }

        [Required, DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [MajeurOuPas]
        public DateTime? DateNaissance { get; set; }

        [Required, StringLength(12)]
        [Phone]
        public string Telephone { get; set; }

        [Required, StringLength(30)]
        [EmailAddress]
        
        public string AdresseMail { get; set; }

        //[Range(typeof(bool), "true", "true", ErrorMessage = "Veuillez indiquer votre situation professionnelle")]
        //[Display(Name ="Etes-vous en poste?")]
        public bool SituationPro { get; set; }

        //[Range(typeof(bool),"true","true", ErrorMessage ="Veuillez indiquer votre mobilité")]
        //[Display(Name ="Etes-vous mobile?")]
        public bool Mobilite { get; set; }

        public SituationFamiliale SitutationFamiliale { get; set; }
        [Display(Name = "Situation Familiale")]
        public byte SituationFamilialeId { get; set; }

        public PoleEmbauche PoleEmbauche { get; set; }
        [Display(Name = "Secteur géographique")]
        public byte PoleEmbaucheId { get; set; }

        public Diplome Diplome { get; set; }

        [Display(Name="Diplôme")]
        public byte DiplomeId { get; set; }
    }
}

HeadHunterProject/HeadHunterProject/Controllers/CandidatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using HeadHunterProject.ViewModel;
using HeadHunterProject.Models;
using System.Data.Entity.Validation;

namespace HeadHunterProject.Controllers
{
    public class CandidatController : Controller
    {
        // GET: Candidat

        private ApplicationDbContext _context;
        public CandidatController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose(); ;
        }
        public ActionResult New()
        {
            var poleEmbauche = _context.PoleEmbauche.ToList();
            var situFamiliale = _context.SituationFamiliale.ToList();
            var viewModel = new CandidatFormViewModel
            {
                Candidat = new Candidat
                {
                    DateNaissance = null
                },              
                
                PoleEmbauche = poleEmbauche,
                SituationFamiliale = situFamiliale,
            };
            return View("CandidatForm",viewModel);
        }
        [HttpPost]
        public ActionResult Save(Candidat candidat)
        {
            if(!ModelState.IsValid)
            {
                var viewModel = new CandidatFormViewModel
                {
                    Candidat = candidat,
                    PoleEmbauche = _context.PoleEmbauche.ToList(),
                    SituationFamiliale = _context.SituationFamiliale.ToList()
                };
                return View("CandidatForm",viewModel);
            }
            if(candidat.Id == 0)
            {
                _context.Candidat.Add(candidat);
            }
            else
            {
                var candidatInDb = _context.Candidat.Single(p => p.Id == candidat.Id);
                candidatInDb.Nom = candidat.Nom;
                candidatInDb.Prenom = candidat.Prenom;
                candidatInDb.DateNaissance = candidat.DateNaissance;
                candidatInDb.Mobilite = candidat.Mobilite;
                candidatInDb.PoleEmbauche = candidat.PoleEmbauche;
                candidatInDb.SitutationFamiliale = candidat.SitutationFamiliale;
                candidatInDb.SituationPro = candidat.SituationPro;
                candidatInDb.Telephone = candidat.Telephone;
                candidatInDb.AdresseMail = candidat.AdresseMail;
            }
            try
            {
               
                _context.SaveChanges();
                
            }
            catch(DbEntityValidationException e)
            {
                Console.WriteLine(e);
            }
            return RedirectToAction("Index", "Home");


        }
           
    }
}

HeadHunterProject/HeadHunterProject/Views/Candidat/CandidatForm.cshtml
@model HeadHunterProject.ViewModel.CandidatFormViewModel
@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="centrage">@Model.Title</h2>

@using (Html.BeginForm("Save", "Candidat"))
{
   
    <div class="centrage">
        @*@Html.ValidationSummary()*@
        <div class="form-group">
            <label for="Nom">Nom</label>
            @Html.TextBoxFor(m => m.Candidat.Nom, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Candidat.Nom)
        </div>
        <div class="form-group">
            <label for="Prenom">Prénom</label>
            @Html.TextBoxFor(m => m.Candidat.Prenom, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Candidat.Prenom)
        </div>
        <div class="form-group">
            <label for="DateNaissance">Date de Naissance</label>
            @Html.TextBoxFor(m => m.Candidat.DateNaissance, "{0:d MMM yyyy}",  new { @class = "form-control", @value = "" })
            @Html.ValidationMessageFor(m => m.Candidat.DateNaissance)
        </div>
        <div class="form-group">
            <label for="Telephone">Telephone</label>
            @Html.TextBoxFor(m => m.Candidat.Telephone, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Candidat.Telephone)
        </div>
        <div class="form-group">
            <label for="AdresseMail">Adresse Mail</label>
            @Html.TextBoxFor(m => m.Candidat.AdresseMail, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Candidat.AdresseMail)
        </div>
        <div class="form-group">
            <label>
                @Html.CheckBoxFor(m => m.Candidat.SituationPro) Etes-vous en poste?
            </label>            
            <label>
                @Html.CheckBoxFor(m => m.Candidat.Mobilite) Etes-vous mobile?
            </label>
        </div>

        <div class="form-group">
            <label for="SituationFamilialeId">Situation Familiale</label>
            @Html.DropDownListFor(m => m.Candidat.SituationFamilialeId, new SelectList(Model.SituationFamiliale, "Id", "Libelle"), "Selectionnez votre situation familiale", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Candidat.SituationFamilialeId)
        </div>
        <div class="form-group">
            <label for="PoleEmbaucheId">Secteur Géographique </label>
            @Html.DropDownListFor(m => m.Candidat.PoleEmbaucheId, new SelectList(Model.PoleEmbauche, "Id", "Libelle"), "Selectionnez votre secteur géographique", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Candidat.PoleEmbaucheId)
        </div>
        @Html.HiddenFor(m => m.Candidat.Id)
        <button type="submit" class="btn btn-primary">Valider</button>
    </div>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}
